version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/python-test
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/install-dependencies
      runas: root
  AfterInstall:
    - location: scripts/after-install
      runas: root

